<?php
$mockIphone = array (
    "result"=>array(
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Apple iPhone 11 - 64GB - New 99.jpg",
            "title"=>"CHUWI heorbook plus 15.6'' window",
            "price"=>array("current_price"=>350, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Apple iPhone 11 - 64GB - New 99.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Apple iPhone 11 - 64GB mobile phone - Genuine.jpg",
            "title"=>"Apple iPhone 11 - 64GB mobile phone - Genuine",
            "price"=>array("current_price"=>1080, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Apple iPhone 11 - 64GB mobile phone - Genuine.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 11 64GB.png",
            "title"=>"Genuine iPhone 11 64GB",
            "price"=>array("current_price"=>230, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 11 64GB.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 12 Pro 128GB.png",
            "title"=>"Genuine iPhone 12 Pro 128GB",
            "price"=>array("current_price"=>340, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 14 Pro Max 256GB VNA.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 14 Pro Max 256GB VNA.png",
            "title"=>"Genuine iPhone 14 Pro Max 256GB VNA",
            "price"=>array("current_price"=>450, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 14 Pro Max 256GB VNA.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 14 Pro 256GB VN.png",
            "title"=>"Genuine iPhone 14 Pro 256GB VN",
            "price"=>array("current_price"=>570, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Genuine iPhone 14 Pro 256GB VN.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/Genuine 64GB iPhone 11 reduced by 2.5 million VND.jpg",
            "title"=>"Genuine 64GB iPhone 11 reduced by 2.5 million VND",
            "price"=>array("current_price"=>560, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/Genuine 64GB iPhone 11 reduced by 2.5 million VND.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone/iPhone 11 (64GB).jpg",
            "title"=>"iPhone 11 (64GB)",
            "price"=>array("current_price"=>640, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone/iPhone 11 (64GB).jpg")
    )
);
$mockLaptop = array (
    "result"=>array(
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Laptops For Home - All series.jpg",
            "title"=>"Laptops For Home - All series",
            "price"=>array("current_price"=>240, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Laptops For Home - All series.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/On hand Samsung Galaxy Book Pro.jpg",
            "title"=>"On hand Samsung Galaxy Book Pro",
            "price"=>array("current_price"=>570, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/On hand Samsung Galaxy Book Pro.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Galaxy Book Pro 13.jpg",
            "title"=>"Samsung Galaxy Book Pro 13",
            "price"=>array("current_price"=>250, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Galaxy Book Pro 13.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Galaxy Book 2 Pro 360.jpg",
            "title"=>"Samsung Galaxy Book 2 Pro 360.jpg",
            "price"=>array("current_price"=>300, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Galaxy Book 2 Pro 360.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Laptop Sound Both Strange and Familiar.jpg",
            "title"=>"Samsung Laptop Sound Both Strange and Familiar",
            "price"=>array("current_price"=>600, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Laptop Sound Both Strange and Familiar.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung laptop 2019.jpg",
            "title"=>"Samsung laptop 2019.jpg",
            "price"=>array("current_price"=>470, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung laptop 2019.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/The 9 Best Laptops of 2023.jpg",
            "title"=>"mock-data/laptop/The 9 Best Laptops of 2023.jpg",
            "price"=>array("current_price"=>400, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/The 9 Best Laptops of 2023.jpg")
    )
);
$mockTV = array (
    "result"=>array(
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/pillips_TV/3.png",
            "title"=>"Philips 242E2F - 24in IPS FHD 3790",
            "price"=>array("current_price"=>570, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/pillips_TV/3.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/pillips_TV/4.png",
            "title"=>"smart tivi sony 50 inch kdl50w660g/zvn3 7800",
            "price"=>array("current_price"=>790, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/pillips_TV/4.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/pillips_TV/5.png",
            "title"=>"Tivi Sharp 32 inch 2T-C32BD1X 3990",
            "price"=>array("current_price"=>700, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/pillips_TV/5.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/pillips_TV/6.png",
            "title"=>"TIVI XIAOMI EA65 2022 SERIES 10490",
            "price"=>array("current_price"=>455, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/pillips_TV/6.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/Tosiba_TV/1.png",
            "title"=>"[Code ELBAU4 4% off 500K single] Smart Nanocell LG 65 Inch 4K TV 65NANO76SQA... 14790",
            "price"=>array("current_price"=>445, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/Tosiba_TV/1.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/Tosiba_TV/2.png",
            "title"=>"[Code ELBAU4 4% off 500K single] Smart UHD LG 43 Inch 4K TV 43UP7720PTC - Model 2021 - Free... 7390",
            "price"=>array("current_price"=>550, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/Tosiba_TV/2.png")
    )
);
$mockData = array (
    "result"=>array(
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Ultra-Thin Touchscreen Laptop - Microsoft Surface.jpg",
            "title"=>"Ultra-Thin Touchscreen Laptop - Microsoft Surface",
            "price"=>array("current_price"=>200, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Ultra-Thin Touchscreen Laptop - Microsoft Surface.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/iphone_apple/1.png",
            "title"=>"iPhone 14 Pro 256GB 27790",
            "price"=>array("current_price"=>570, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/iphone_apple/1.png"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Unveils Two New PCs with Signature Style and Performance - Samsung  US Newsroom.jpg",
            "title"=>"Samsung Unveils Two New PCs with Signature Style and Performance - Samsung  US Newsroom",
            "price"=>array("current_price"=>250, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Unveils Two New PCs with Signature Style and Performance - Samsung  US Newsroom.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Galaxy Book 2 Pro 360.jpg",
            "title"=>"Samsung Galaxy Book 2 Pro 360.jpg",
            "price"=>array("current_price"=>300, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Galaxy Book 2 Pro 360.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Laptop Sound Both Strange and Familiar.jpg",
            "title"=>"Samsung Laptop Sound Both Strange and Familiar",
            "price"=>array("current_price"=>600, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Laptop Sound Both Strange and Familiar.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung laptop 2019.jpg",
            "title"=>"Samsung laptop 2019.jpg",
            "price"=>array("current_price"=>470, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung laptop 2019.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Unveils Two New PCs with Signature Style and Performance - Samsung  US Newsroom.jpg",
            "title"=>"Samsung Unveils Two New PCs with Signature Style and Performance - Samsung  US Newsroom",
            "price"=>array("current_price"=>450, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/Samsung Unveils Two New PCs with Signature Style and Performance - Samsung  US Newsroom.jpg"),
        array("thumbnail"=>"http://localhost/pricechecker/mock-data/laptop/The 9 Best Laptops of 2023.jpg",
            "title"=>"mock-data/laptop/The 9 Best Laptops of 2023.jpg",
            "price"=>array("current_price"=>400, "currency"=>"$"),
            "url"=>"http://localhost/pricechecker/mock-data/laptop/The 9 Best Laptops of 2023.jpg")
    )
);